---
- hosts: all
  tasks:
    - name:
      apt:
       update_cache: yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    - name:
      command: apt list --upgradable
      register: updates
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    - debug: var=updates.stdout_lines
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
    - name: check for updates (yum)
      yum: list=updates update_cache=true
      register: yumoutput
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - debug: msg="{{ yumoutput.results | map(attribute='name') | join(', ')}}"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - debug: msg="{{ yumoutput.results | map(attribute='name') }}" 
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
