########################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ########################################################################
########################################################################
- name: PlayBook for Install updates on ALL HOSTS
  hosts: CS-WTES01-T-SRV_4227fe7d-1db6-6358-33fe-b7c809ff95a0 #all
  gather_facts: no
  remote_user: ansible
  #become_method: sudo
  become: True
  vars:
    run: false
    reboot: false
  tasks:
# Linux YUM
    - name: LINUX (YUM)
      dnf: list=upgrades
      register: yumoutput
      when: config.guestId == 'rhel9_64Guest' or config.guestId == 'centos64Guest' or config.guestId == 'centos7_64Guest' or config.guestId == 'centos8_64Guest' and "summary.runtime.powerState" == 'poweredOn'
    - debug:
        msg: "{{yumoutput.msg}}"
      when: config.guestId == 'rhel9_64Guest' or config.guestId == 'centos64Guest' or config.guestId == 'centos7_64Guest' or config.guestId == 'centos8_64Guest' and "summary.runtime.powerState" == 'poweredOn'

# Linux APT
    - name: LINUX (APT-UPDATE-CACHE)
      ansible.builtin.apt:
        update-cache: true
      when: config.guestId == 'ubuntu64Guest' or config.guestId == 'debian11_64Guest' or config.guestId == 'debian8_64Guest' and summary.runtime.powerState == 'poweredOn'
    - name: LINUX (APT-LIST)
      ansible.builtin.command: apt list --upgradable
      register: apt_simulate
      when: config.guestId == 'ubuntu64Guest' or config.guestId == 'debian11_64Guest' or config.guestId == 'debian8_64Guest' and summary.runtime.powerState == 'poweredOn'
    - debug:
        var: apt_simulate.msg
      when: config.guestId == 'ubuntu64Guest' or config.guestId == 'debian11_64Guest' or config.guestId == 'debian8_64Guest' and summary.runtime.powerState == 'poweredOn'

# Windows
    - name: WINDOWS
      ansible.windows.win_updates:
        category_names: 
          - SecurityUpdates
          - CriticalUpdates
          - Updates
        state: searched
      register: ansible_wu
      when: config.guestId == 'windows9Server64Guest' or config.guestId == 'windows2019srv_64Guest' or config.guestId == 'windows2019srvNext_64Guest' or config.guestId == 'windows9_64Guest' and summary.runtime.powerState == 'poweredOn'
    #- name: Create Dictionary from var ansible_wu
    #  debug: msg={{ ("{{ansible_wu}}" |  from_json) }}
    #  set_fact:
    #    title: "{{ansible_wu.filtered_updates}}"
    #  when: distribution == "Windows"
    #- name: Create Final log
    #  set_fact:
    #    titles: "{{title | community.general.json_query('*.title')}}"
    #  when: distribution == "Windows"
    - name: Print final Log
      debug:
     #   msg: "{{ ansible_wu | list }}"
     # when: ansible_pkg_mgr == 'win'
        msg: |
           {% for k in ansible_wu.updates %}
           {{ ansible_wu.updates[k].title }}
           {% endfor %}
      when: config.guestId == 'windows9Server64Guest' or config.guestId == 'windows2019srv_64Guest' or config.guestId == 'windows2019srvNext_64Guest' or config.guestId == 'windows9_64Guest' and summary.runtime.powerState == 'poweredOn'
