#######################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ######################################################################
########################################################################
- name: create users from list
  hosts: localhost
  tasks:
    - name: extract Username from all dictionaries
      var:
        msg: "{{ users.split ('\n') }}"
      
    
#      loop: "{{ users.list }}"
     #delegate_to: localhost 
   #- name: create users from the csv
   #   user:
   #     name: "{{ item.Username }}"
   #     uid: "{{ item.UID }}"
   #     groups: "{{ item.Groups }}"
   #     append: true
   #     password: "{{ item.Password | password_hash('sha512') }}"
   #     comment: "{{ item.First_Name }} {{ item.Last_Name }}"
   #     state: present
   #  loop: "{{ user_list.list }}"
   #  become: true
