#######################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ######################################################################
########################################################################
- name: create users from list
  hosts: localhost
  utente:
    user: "{{ Username }}"
    name1: "{{ First_Name }}"
    name2: "{{ Last_Name }}"
    password: "{{ Password }}"
  
  tasks:
    - name: extract Username from all dictionaries
      debug:
        msg:: "{{ utente.Username }}"
        #var2: "{{ First_Name }}"
        #var3: "{{ Last_Name }}"
        #var4: "{{ Password }}"
        #var: "{{ users }}"
    

    #- name: create users from the csv
    #  user:
    #    name: "{{ item.Username }}"
    #    append: true
    #    password: "{{ item.Password | password_hash('sha512') }}"
    #    comment: "{{ item.First_Name }} {{ item.Last_Name }}"
    #    state: present
     #loop: "{{ user_list.list }}"
     #become: true
        #var: "{{ users }}"
      #loop: "{{ users }}  
    
#      loop: "{{ users.list }}"
     #delegate_to: localhost 
   #- name: create users from the csv
   #   user:
   #     name: "{{ item.Username }}"
   #     uid: "{{ item.UID }}"
   #     groups: "{{ item.Groups }}"
   #     append: true
   #     password: "{{ item.Password | password_hash('sha512') }}"
   #     comment: "{{ item.First_Name }} {{ item.Last_Name }}"
   #     state: present
   #  loop: "{{ user_list.list }}"
   #  become: true
