#######################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ######################################################################
########################################################################
- name: create users from list
  hosts: localhost
  #vars:
  #  Username: "{{ Username }}"
  #  First_Name: "{{ First_Name }}"
  #  Last_Name: "{{ Last_Name }}"
  #  password: "{{ Password }}"
  #  users: "{{ users }}"
  tasks:
    - name: extract User dictionaries
      debug:
        msg: "{{ item }}"
    #  loop: "{{ Username | dict2items }}"
      loop: 
        - "{{ Username.split('\n') |list }}"
        - "{{ Password.split('\n') |list }}"
      register: elenco
    - name: Iterate over multiple-key dictionary using loop with 'dict' lookup - succeeds
      vars:
        cur_item: "key={{current_item.key}} value={{current_item.value}}"
      debug: var=cur_item
      loop:
        "{{lookup('dict', Username)}}"
      loop_control:
        loop_var: current_item
    - name: Print server role info
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ elenco }}"
    #- name: extract User from users
    #  debug:
        #msg: "{{ users | split(',') }}"
    #    msg: "{{ msg | split(',') }}"
      #loop: "{{users}}
      #var2: "{{ First_Name }}"
      #var3: "{{ Last_Name }}"
        #var4: "{{ Password }}"
        #var: "{{ users }}"
    

    #- name: create users from the csv
    #  user:
    #    name: "{{ item.Username }}"
    #    append: true
    #    password: "{{ item.Password | password_hash('sha512') }}"
    #    comment: "{{ item.First_Name }} {{ item.Last_Name }}"
    #    state: present
     #loop: "{{ user_list.list }}"
     #become: true
        #var: "{{ users }}"
      #loop: "{{ users }}  
    
#      loop: "{{ users.list }}"
     #delegate_to: localhost 
   #- name: create users from the csv
   #   user:
   #     name: "{{ item.Username }}"
   #     uid: "{{ item.UID }}"
   #     groups: "{{ item.Groups }}"
   #     append: true
   #     password: "{{ item.Password | password_hash('sha512') }}"
   #     comment: "{{ item.First_Name }} {{ item.Last_Name }}"
   #     state: present
   #  loop: "{{ user_list.list }}"
   #  become: true
