#######################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ######################################################################
########################################################################
- name: create users from csv file
  hosts: localhost
  tasks:
    - name: display user_list data
      debug:
      var: users.list
    - name: Check users
      debug:
      msg: "{{ item.Username }}"
      loop: "{{ users }}"
     #delegate_to: localhost 
   #- name: create users from the csv
   #   user:
   #     name: "{{ item.Username }}"
   #     uid: "{{ item.UID }}"
   #     groups: "{{ item.Groups }}"
   #     append: true
   #     password: "{{ item.Password | password_hash('sha512') }}"
   #     comment: "{{ item.First_Name }} {{ item.Last_Name }}"
   #     state: present
   #  loop: "{{ user_list.list }}"
   #  become: true
