#######################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ######################################################################
########################################################################
- name: create users from list
  hosts: localhost
  vars:
    Username: "{{ Username }}"
    First_Name: "{{ First_Name }}"
    Last_Name: "{{ Last_Name }}"
    password: "{{ Password }}"
  tasks:
    - name: extract User dictionaries
      debug:
        msg: "{{ Username }},{{ First_Name }},{{ Last_Name }},{{ Password }}"
    - name: extract User from users
      debug:
        #msg: "{{ users | split(',') }}"
        msg: "{{ users | split(',') }}"
      #loop: "{{users}}
      #var2: "{{ First_Name }}"
      #var3: "{{ Last_Name }}"
        #var4: "{{ Password }}"
        #var: "{{ users }}"
    

    #- name: create users from the csv
    #  user:
    #    name: "{{ item.Username }}"
    #    append: true
    #    password: "{{ item.Password | password_hash('sha512') }}"
    #    comment: "{{ item.First_Name }} {{ item.Last_Name }}"
    #    state: present
     #loop: "{{ user_list.list }}"
     #become: true
        #var: "{{ users }}"
      #loop: "{{ users }}  
    
#      loop: "{{ users.list }}"
     #delegate_to: localhost 
   #- name: create users from the csv
   #   user:
   #     name: "{{ item.Username }}"
   #     uid: "{{ item.UID }}"
   #     groups: "{{ item.Groups }}"
   #     append: true
   #     password: "{{ item.Password | password_hash('sha512') }}"
   #     comment: "{{ item.First_Name }} {{ item.Last_Name }}"
   #     state: present
   #  loop: "{{ user_list.list }}"
   #  become: true
