########################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ########################################################################
########################################################################
- name: PlayBook for Install VM on Datacenter
  hosts: localhost
  tasks:
  - name: Clone a virtual machine from Linux template and customize
    community.vmware.vmware_guest:
      datacenter: "{{vcenter_name}}"
      validate_certs: no
      folder: "{{vcenter_folder}}"
      cluster: "{{vcenter_cluster}}"
      name: "{{vm_hostname}}"
      template: "{{vm_template}}"
      state: powered-on
      disk:
        - size_gb: "{{disk_size_gb}}"
          type: eagerzeroedthick
          datastore: "{{vcenter_datastore}}"
      hardware:
        memory_mb: "{{vm_memory}}"
        num_cpus: "{{vm_cpu}}"
        scsi: paravirtual
        #boot_firmware: "efi"
      networks:
        - name: "{{network_name}}"
          ip: "{{network_ip}}"
          netmask: "{{network_netmask}}"
          gateway: "{{network_gw}}"
          domain: "{{network_domain}}"
          type: "{{ip_mode}}"
          start_connected: True
          dns_servers:
            - "{{dns_servers[0]}}"
      customization:
        hostname: "{{ vm_hostname }}"
        dns_servers:
          - "{{dns_servers[0]}}"
  - name: "Wait for server starting up." 
    wait_for:
      port: 22
      host: "{{ network_ip }}"
      delay: 10
