########################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ########################################################################
########################################################################
- name: PlayBook for Install WinVM on Datacenter DEV
  hosts: localhost
  tasks:
  - name: Clone a virtual machine from Windows template and customize
    community.vmware.vmware_guest:
      #hostname: "{{vcenter_hostname}}"
      #username: "{{vcenter_username}}"
      #password: "{{vcenter_password}}"
      datacenter: "{{vcenter_name}}"
      validate_certs: no
      folder: "{{vcenter_folder}}"
      cluster: "{{vcenter_cluster}}"
      name: "{{vm_hostname}}"
      state: poweredon
      template: "{{vm_template}}"
      disk:
        - size_gb: "{{disk_size_gb}}"
          type: eagerzeroedthick
            #state: present
            #scsi_controller: 0
            #unit_number: 0
          datastore: "{{vcenter_datastore}}"
      hardware:
        memory_mb: "{{vm_memory}}"
        num_cpus: "{{vm_cpu}}"
        scsi: paravirtual
        memory_reservation_lock: true
        mem_limit: 8096
        mem_reservation: 4096
        cpu_shares_level: "high"
        mem_shares_level: "high"
        cpu_limit: 8096
        cpu_reservation: 4096
          #max_connections: 5
        hotadd_cpu: true
        hotremove_cpu: true
        hotadd_memory: false
        version: 12 # Hardware version of virtual machine
        boot_firmware: "efi"
      networks:
        - name: "{{network_name}}"
          ip: "{{network_ip}}"
          netmask: 255.255.255.0
          gateway: "{{network_gw}}"
          domain: "{{network_domain}}"
          dns_servers:
            - "{{dns_servers[0]}}"
            - "{{dns_servers[1]}}"
          type: "{{ip_mode}}"
- name: Add host to group 'just_created' with variable foo=42
  ansible.builtin.add_host:
    groups:
    - WINDOWS
    hostname: '{{ vm_hostname }}'
    ansible_ssh_host: '{{ network_ip }}'
