########################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ########################################################################
########################################################################
- name: PlayBook for Install WinVM on Datacenter DEV
  hosts: localhost
  tasks:
  - name: Clone a virtual machine from Windows template and customize
    community.vmware.vmware_guest:
      datacenter: "{{vcenter_name}}"
      validate_certs: no
      folder: "{{vcenter_folder}}"
      cluster: "{{vcenter_cluster}}"
      name: "{{vm_hostname}}"
      template: "{{vm_template}}"
      state: present
      disk:
        - size_gb: "{{disk_size_gb}}"
          type: eagerzeroedthick
          datastore: "{{vcenter_datastore}}"
      hardware:
        memory_mb: "{{vm_memory}}"
        num_cpus: "{{vm_cpu}}"
        scsi: lsilogicsas
      networks:
        - name: "{{network_name}}"
          ip: "{{network_ip}}"
          netmask: "{{network_netmask}}"
          gateway: "{{network_gw}}"
          domain: "{{network_domain}}"
          type: "{{ip_mode}}"
          start_connected: True
          dns_servers:
            - "{{dns_servers[0]}}"
            - "{{dns_servers[1]}}"
      customization:
        password: "{{ vm_password }}"
        existing_vm: True
        domain: "{{network_domain}}"
        hostname: "{{vm_hostname}}"
        timezone: 110
        dns_servers:
            - "{{dns_servers[0]}}"
            - "{{dns_servers[1]}}"
    register: deploy
  - name: "Wait for server starting up." 
    wait_for:
      timeout: 400
  - name: "Refresh Inventory."
    meta: refresh_inventory
