########################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ########################################################################
########################################################################
- name: PlayBook for Install VM on Datacenter
  hosts: localhost
  gather_facts: no
  tasks:
# Linux YUM
  - name: Clone a virtual machine from Linux template and customize
    community.vmware.vmware_guest:
      #hostname: "{{vcenter_hostname}}"
      #username: "{{vcenter_username}}"
      #password: "{{vcenter_password}}"
      datacenter: "{{vcenter_name}}"
      validate_certs: no
      folder: "{{vcenter_folder}}"
      cluster: "{{vcenter_cluster}}"
      name: "{{vm_hostname}}"
      state: poweredon
      template: "{{vm_template}}"
      disk:
        - size_gb: "{{disk_size_gb}}"
          type: eagerzeroedthick
            #state: present
            #scsi_controller: 0
            #unit_number: 0
          datastore: "{{vcenter_datastore}}"
    # Add another disk from an existing VMDK
      #- filename: "[datastore1] testvms/testvm_2_1/testvm_2_1.vmdk"
      hardware:
        memory_mb: "{{vm_memory}}"
        num_cpus: "{{vm_cpu}}"
        scsi: paravirtual
        #memory_reservation_lock: true
        #mem_limit: 8096
        #mem_reservation: 4096
        #cpu_shares_level: "high"
        #mem_shares_level: "high"
        #cpu_limit: 8096
        #cpu_reservation: 4096
          #max_connections: 5
        #hotadd_cpu: true
        #hotremove_cpu: true
        #hotadd_memory: false
        #version: 12 # Hardware version of virtual machine
        #boot_firmware: "efi"
      networks:
        - name: "{{network_name}}"
          ip: "{{network_ip}}"
          netmask: "{{network_netmask}}"
          gateway: "{{network_gw}}"
          domain: "{{network_domain}}"
          type: "{{ip_mode}}"
          start_connected: True
          dns_servers:
            - "{{dns_servers[0]}}"
      customization:
        hostname: "{{ vm_hostname }}"
        #timezone: 110
        dns_servers:
            - "{{dns_servers[0]}}"
      wait_for_customization: true
      wait_for_ip_address: true
    register: deploy
  #- name: Add host to group
  #  ansible.builtin.add_host:
  #    groups:
  #      - LINUX
  #      - DEBIAN-UBUNTU
  #    hostname: '{{ vm_hostname }}'
  #    ansible_ssh_host: '{{ network_ip }}'
  #- name: Refresh inventory to ensure new instances exist in inventory
  #  meta: refresh_inventory
