########################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ########################################################################
########################################################################
- name: PlayBook for Install WinVM on Datacenter DEV
  hosts: localhost
  tasks:
  - name: Clone a virtual machine from Windows template and customize
    community.vmware.vmware_guest:
      datacenter: "{{vcenter_name}}"
      validate_certs: no
      folder: "{{vcenter_folder}}"
      cluster: "{{vcenter_cluster}}"
      name: "{{vm_hostname}}"
      template: "{{vm_template}}"
      state: poweredon
      disk:
        - size_gb: "{{disk_size_gb}}"
          type: eagerzeroedthick
          datastore: "{{vcenter_datastore}}"
      hardware:
        memory_mb: "{{vm_memory}}"
        num_cpus: "{{vm_cpu}}"
        scsi: lsilogicsas
        boot_firmware: "efi"
      networks:
        - name: "{{network_name}}"
          ip: "{{network_ip}}"
          netmask: 255.255.255.0
          gateway: "{{network_gw}}"
          domain: "{{network_domain}}"
          dns_servers:
            - "{{dns_servers[0]}}"
            - "{{dns_servers[1]}}"
          type: "{{ip_mode}}"
      customization:
        domain: "{{network_domain}}"
        hostname: "{{vm_hostname}}"
        timezone: 110
        dns_servers:
            - "{{dns_servers[0]}}"
            - "{{dns_servers[1]}}"
      wait_for_customization: false
      wait_for_ip_address: false
    register: deploy
    delegate_to: localhost
  - name: START VM
    community.vmware.vmware_guest_powerstate:
      state: powered-on
    delegate_to: localhost
    register: powerup
  - name: PRINT NAME
    debug: 
      var: "{{deploy.instance.hw_name}}.{{deploy.instance.hw_product_uuid}}"
