#######################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# #####################################################################
#######################################################################
- name: PlayBook for Resize FS Windows
  hosts: "{{vm_hostname}}_*"
  gather_facts: no
  remote_user: ansible
  become_method: runas
  become: True
  tasks:
    - name: Create temporary build directory
      ansible.windows.win_tempfile:
        state: directory
        suffix: build
    - name: Resize FS 
      win_shell: C:\\criticalservice\\bin\\extend_volume_c.ps1
