#######################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# #####################################################################
#######################################################################
- name: PlayBook for Resize FS Windows
  hosts: "{{vm_hostname}}_*"
  gather_facts: no
  remote_user: ansible
  become_method: runas
  become: True
  tasks:
    - name: Create temporary build directory
      ansible.windows.win_tempfile:
        state: directory
        suffix: build
    - name: Sleep for 300 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 300
      delegate_to: localhost
    - name: wait for the server to come back
      wait_for:
        host: "{{vm_hostname}}"
        port: 22
        delay: 15
      delegate_to: localhost
      ignore_errors: true
    - name: Resize FS 
      win_shell: C:\\criticalservice\\bin\\extend_volume_c.ps1
