#######################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# #####################################################################
#######################################################################
- name: PlayBook for Resize FS Windows
  hosts: "{{vm_hostname}}_*"
  delegate_to: localhost
  gather_facts: no
  remote_user: ansible
  become_method: runas
  become: True
  tasks:
    - name: Sleep for 30 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 30
      delegate_to: localhost
    - name: Resize FS 
      win_shell: C:\\criticalservice\\bin\\extend_volume_c.ps1
      delegate_to: localhost
