########################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ########################################################################
########################################################################
- name: PlayBook for Install updates on ALL HOSTS
  hosts: "{{vm_hostname}}_*"
  gather_facts: yes
  remote_user: ansible
  #become_method: sudo
  become: True
  tasks:
    - name: Resize FS 
      ansible.builtin.command:
        cmd: /bin/sh /home/ansible/bin/resize_fs.sh
      register: fs_resize
