#######################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# #####################################################################
#######################################################################
- name: PlayBook for Resize FS DEB
  hosts: "{{vm_hostname | upper}}_*"
  remote_user: ansible
  gather_facts: no
  tasks:
    - name: Resize FS 
      ansible.builtin.command:
        cmd: /bin/sh /home/ansible/bin/resize_fs.sh
      register: fs_resize    
