- name: Include a play after another play
  ansible.builtin.import_playbook: deployVMLinux.yml
  hosts: "{{deploy.instance.hw_name}}.{{deploy.instance.hw_product_uuid}}"
  gather_facts: no
  remote_user: ansible
  #become_method: sudo
  become: True
  tasks:
  - name: Resize FS 
    ansible.builtin.command:
      cmd: /bin/sh /home/ansible/bin/resize_fs.sh
    register: fs_resize
