########################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# ########################################################################
########################################################################
- name: PlayBook for Resize FS DEB
  hosts: "{{vm_hostname}}_*"
  remote_user: ansible
  gather_facts: no
  #become_user: ansible
  #become_method: sudo
  #become: True
  tasks:
    - name: Sleep for 30 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 30
      delegate_to: localhost
    - name: Resize FS 
      ansible.builtin.command:
        cmd: sudo /home/ansible/bin/resize_fs.sh
      register: fs_resize
