- hosts: all
  gather_facts: no
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
      register: infoVM
        #filter: "*"
        #gather_subset: ["all"]
        #fact_path: /etc/ansible/facts.d
        #gather_timeout: 11
    - name: Print
      ansible.builtin.debug: 
        msg: "{{item.key}}"
        
