- hosts: all
  tasks:
    - name: Gather facts
      setup:
        filter: "*"
        gather_subset: ["all"]
        fact_path: /etc/ansible/facts.d
        gather_timeout: 11
        debug:
          msg: ansible_facts
