- hosts: all
  gather_facts: yes
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
      register: infoVM
        #filter: "*"
        #gather_subset: ["all"]
        #fact_path: /etc/ansible/facts.d
        #gather_timeout: 11
    - name: Print infoVM
      ansible.builtin.debug:
        msg: "{{infoVM}} {{ansible_distribution_release}}"
    - name: Print Linux
      ansible.builtin.debug:
        msg: "{{ansible_distribution}} {{ansible_distribution_release}}"
      when: distribution == "Linux"
    - name: Print Windows
      ansible.builtin.debug:
        msg: "{{ansible_os_name}}"
      when: distribution == "Windows"
