- hosts: all
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
      register: infoVM
        #filter: "*"
        #gather_subset: ["all"]
        #fact_path: /etc/ansible/facts.d
        #gather_timeout: 11
    - name: Print
      ansible.builtin.debug: 
        var: infoVM 
