# host should be a member of domain ansible.vagrant; module will ensure the hostname is mydomainclient
# and will use the passed credentials to join domain if necessary.
# Ansible connection should use local credentials if possible.
# If a reboot is required, the second task will trigger one and wait until the host is available.
- hosts: "{{vm_hostname}}_*"
  remote_user: ansible
  become_method: runas
  become: True
  gather_facts: false
  tasks:
    - ansible.windows.win_domain_membership:
        dns_domain_name: criticalservice.test
        hostname: "{{vm_hostname}}"
        domain_admin_user: '{{ domain_admin_user }}'
        domain_admin_password: '{{ domain_admin_password }}'
        domain_ou_path: '{{ mv_ou }}' #"OU=Server Reboot 4:00,OU=02_Servers,OU=01-CRITICALSERVICE,DC=criticalservice,DC=test"
        #domain_ou_path: "OU=Linux_SRV,OU=02_Servers,OU=01-CRITICALSERVICE,DC=criticalservice,DC=test"
        state: domain
      register: domain_state
