#######################################################################
#######################################################################
# PlayBook create by Cirillo Giuseppe
# #####################################################################
#######################################################################
---
- name: PlayBook Join to domain criticalservice.test
  gather_facts: yes
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /criticalservice/bin
    state: directory
    
- name: Install packages
  ansible.builtin.apt:
    pkg: [realmd, sssd, sssd-tools, libnss-sss, libpam-sss, adcli, samba-common-bin, oddjob, oddjob-mkhomedir, packagekit, net-tools, krb5-user]
  when: ansible_distribution == "Ubuntu" #and (ansible_distribution_major_version == "22" or ansible_distribution_major_version == "20")
  tags:
    - install_pkgs

- name: Install packages
  ansible.builtin.yum:
    name: [sssd, realmd, oddjob, oddjob-mkhomedir, adcli, samba-common, samba-common-tools, krb5-workstation, openldap-clients, policycoreutils-python]
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - install_pkgs

- name: Install packages
  ansible.builtin.dnf:
    name: [sssd, realmd, oddjob, oddjob-mkhomedir, adcli, samba-common, samba-common-tools, krb5-workstation]
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
  tags:
    - install_pkgs
    
- name: Add sudo-entry for linux-groups-admin
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "domain users@criticalservice.test ALL=(ALL) NOPASSWD: ALL"

- name: Add domain-entry on resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    state: present
    line: "domain criticalservice.test"
  
- name: Join domain 
    ansible.builtin.command:
      cmd: "{{ item }}"
    with_items:
      - realm leave
      - realm discover -v cs-dcln01-t-srv.criticalservice.test
    ignore_errors: true

  - name: Join domain realm join
    ansible.builtin.shell: echo "Br1sp0tt0C3r3al1x!" | realm join -v -U test.ansij --computer-ou=OU=Linux_SRV,OU=02_Servers,OU=01-CRITICALSERVICE,DC=criticalservice,DC=test CRITICALSERVICE.TEST
      
  - name: Prepare sssd.conf
    ansible.builtin.copy:
      dest: "/etc/sssd/sssd.conf"
      content: |
        [sssd]
        domains = criticalservice.test
        config_file_version = 2
        services = nss, pam, sudo
        default_domain_suffix = criticalservice.test
        [domain/criticalservice.test]
        default_shel= /bin/bash
        ad_server = cs-dcln01-t-srv.criticalservice.test
        krb5_store_password_if_offline = True
        cache_credentials = True
        krb5_realm = CRITICALSERVICE.TEST
        realmd_tags = manages-system joined-with-adcli
        id_provider = ad
        fallback_homedir = /home/%u
        ad_domain = criticalservice.test
        use_fully_qualified_names = True
        ldap_id_mapping = True
        ad_gpo_access_control = permissive
        simple_allow_groups = Group_Linux_Access@criticalservice.test
        access_provider = ad
        #sudo_provider = ldap
        ldap_uri = ldap://cs-dcln01-t-srv.criticalservice.test
        ldap_sudo_search_base = dc= criticalservice,dc=test
        ldap_sudo_full_refresh_interval=86400
        ldap_sudo_smart_refresh_interval=3600
  
  - name: Add domain-entry on resolv.conf
    lineinfile:
      path: /etc/pam.d/common-session
      state: present
      line: "session optional pam_mkhomedir.so skel=/etc/skel umask=077"
      
