- hosts: "{{vm_hostname}}_*"
  remote_user: ansible
  become_method: runas
  become: True
  gather_facts: false
  tasks:       
    - ansible.windows.win_domain_membership:
        workgroup_name: workgroup
        domain_admin_user: '{{ domain_admin_user }}'
        domain_admin_password: '{{ domain_admin_password }}'
        state: workgroup
    - name: Remove linux computer from Active Directory using a windows machine
      win_domain_computer:
        name: "{{vm_hostname}}"
        state: absent
