---
- hosts: all
  tasks:
    - name: Update repository cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_distribution == "CentOS"
      tags:
        - update_repo
