---
galaxy_info:
  author: "Giuseppe Cirillo"
  description: 'Update tasks for RHEL/Centos'
  company: Criticalservice
  license: Opem
  min_ansible_version: '2.2'
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - system
    - basic
    - updates
dependencies: []
